name = "System Setup"

[[data]]
name = "Development Setup"
description = "This script is designed to handle the installation of various development dependencies and tools across different Linux distributions"
script = "dev-setup.sh"
task_list = "I"

[[data]]
name = "Full System Cleanup"
description = "This script is designed to remove unnecessary packages, clean old cache files, remove temporary files, and to empty the trash."
script = "system-cleanup.sh"
task_list = "RP PFM"
multi_select = false

[[data]]
name = "Full System Update"
description = "This command updates your system to the latest packages available for your distro"
script = "system-update.sh"
task_list = "PFM"
multi_select = false

[[data]]
name = "Gaming Dependencies"
description = "This script is designed to handle the installation of gaming dependencies across different Linux distributions"
script = "gaming-setup.sh"
task_list = "I"

[[data]]
name = "Fix Finder"
description = "Finder optimizations for people without a mental disorder."
script = "fix-finder.sh"
task_list = "I PFM"

[[data]]
name = "Remove Animations"
description = "This script is designed to remove snap packages and the snapd service from your system"
script = "remove-animations.sh"
task_list = "RP"

[[data]]
name = "TTY Fonts"
description = "This Script will set the default TTY font to Terminus size 32 Bold"
script = "terminus-tty.sh"
task_list = "I PFM"
