name: F# Checks

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - '**/*.fs'
      - '**/*.fsproj'
      - 'MacUtilGUI/**'
  pull_request:
    branches: ["main"]
    paths:
      - '**/*.fs'
      - '**/*.fsproj'
      - 'MacUtilGUI/**'

jobs:
  lints:
    name: F# Build and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Cache .NET packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore MacUtilGUI/MacUtilGUI.fsproj

      - name: Build project
        run: dotnet build MacUtilGUI/MacUtilGUI.fsproj --configuration Release --no-restore

      - name: Check F# formatting
        run: dotnet fantomas --check MacUtilGUI/
